[2024-07-14T12:52:23.559+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T12:52:23.629+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pleaserun.fit_prediction scheduled__2024-07-14T11:30:00+00:00 [queued]>
[2024-07-14T12:52:23.660+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pleaserun.fit_prediction scheduled__2024-07-14T11:30:00+00:00 [queued]>
[2024-07-14T12:52:23.660+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T12:52:23.973+0100] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fit_prediction> on 2024-07-14 11:30:00+00:00
[2024-07-14T12:52:24.122+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pleaserun', 'fit_prediction', 'scheduled__2024-07-14T11:30:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpgv3c6xxz']
[2024-07-14T12:52:24.128+0100] {standard_task_runner.py:91} INFO - Job 10: Subtask fit_prediction
[2024-07-14T12:52:24.128+0100] {logging_mixin.py:188} WARNING - /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16425) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T12:52:24.131+0100] {standard_task_runner.py:63} INFO - Started process 16449 to run task
[2024-07-14T12:52:24.611+0100] {task_command.py:426} INFO - Running <TaskInstance: pleaserun.fit_prediction scheduled__2024-07-14T11:30:00+00:00 [running]> on host MAKs-MacBook-Pro.local
[2024-07-14T12:52:25.699+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pleaserun' AIRFLOW_CTX_TASK_ID='fit_prediction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T11:30:00+00:00'
[2024-07-14T12:52:25.701+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T12:52:27.449+0100] {forecaster.py:961} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2024-07-14T12:52:27.860+0100] {filesystem.py:118} DEBUG - input tempfile: /var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpyv72yb3j/_yvhzc5v.json
[2024-07-14T12:52:31.867+0100] {filesystem.py:118} DEBUG - input tempfile: /var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpyv72yb3j/9bnmeq1v.json
[2024-07-14T12:52:31.879+0100] {model.py:2042} DEBUG - idx 0
[2024-07-14T12:52:31.879+0100] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2024-07-14T12:52:31.880+0100] {model.py:2055} DEBUG - CmdStan args: ['/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57323', 'data', 'file=/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpyv72yb3j/_yvhzc5v.json', 'init=/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpyv72yb3j/9bnmeq1v.json', 'output', 'file=/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpyv72yb3j/prophet_modelubjln7dp/prophet_model-20240714125231.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2024-07-14T12:52:31.884+0100] {logging_mixin.py:188} WARNING - 12:52:31 - cmdstanpy - INFO - Chain [1] start processing
[2024-07-14T12:52:31.883+0100] {model.py:2058} INFO - Chain [1] start processing
[2024-07-14T12:54:02.633+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T12:54:02.651+0100] {process_utils.py:132} INFO - Sending 15 to group 16449. PIDs of all processes in the group: [16459, 16449]
[2024-07-14T12:54:02.652+0100] {process_utils.py:87} INFO - Sending the signal 15 to group 16449
[2024-07-14T12:54:02.653+0100] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-14T12:54:02.660+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T12:54:02.685+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mak/Desktop/Code_With_Me/Sentiment project/dags/dag1.py", line 96, in fit_prediction
    p.fit(fit_data)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/prophet/forecaster.py", line 1232, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/prophet/models.py", line 121, in fit
    self.stan_fit = self.model.optimize(**args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cmdstanpy/model.py", line 644, in optimize
    self._run_cmdstan(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cmdstanpy/model.py", line 2087, in _run_cmdstan
    line = proc.stdout.readline()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-14T12:54:02.709+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pleaserun, task_id=fit_prediction, run_id=scheduled__2024-07-14T11:30:00+00:00, execution_date=20240714T113000, start_date=20240714T115223, end_date=20240714T115402
