[2024-07-13T19:14:38.209+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T19:14:38.393+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hhh.fit_prediction manual__2024-07-13T18:01:49.117943+00:00 [queued]>
[2024-07-13T19:14:39.782+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hhh.fit_prediction manual__2024-07-13T18:01:49.117943+00:00 [queued]>
[2024-07-13T19:14:39.783+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-13T19:14:39.825+0100] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fit_prediction> on 2024-07-13 18:01:49.117943+00:00
[2024-07-13T19:14:39.848+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'hhh', 'fit_prediction', 'manual__2024-07-13T18:01:49.117943+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dg1.py', '--cfg-path', '/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmp16vl3q4w']
[2024-07-13T19:14:39.850+0100] {standard_task_runner.py:91} INFO - Job 27: Subtask fit_prediction
[2024-07-13T19:14:39.925+0100] {logging_mixin.py:188} WARNING - /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8804) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-13T19:14:39.926+0100] {standard_task_runner.py:63} INFO - Started process 8842 to run task
[2024-07-13T19:14:39.997+0100] {task_command.py:426} INFO - Running <TaskInstance: hhh.fit_prediction manual__2024-07-13T18:01:49.117943+00:00 [running]> on host MAKs-MacBook-Pro.local
[2024-07-13T19:14:40.414+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='hhh' AIRFLOW_CTX_TASK_ID='fit_prediction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T18:01:49.117943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T18:01:49.117943+00:00'
[2024-07-13T19:14:40.423+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T19:14:41.502+0100] {forecaster.py:961} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2024-07-13T19:14:41.879+0100] {filesystem.py:118} DEBUG - input tempfile: /var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpfaybqyq_/f7o7ops4.json
[2024-07-13T19:14:45.032+0100] {filesystem.py:118} DEBUG - input tempfile: /var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpfaybqyq_/tlim4d49.json
[2024-07-13T19:14:45.034+0100] {model.py:2042} DEBUG - idx 0
[2024-07-13T19:14:45.035+0100] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2024-07-13T19:14:45.035+0100] {model.py:2055} DEBUG - CmdStan args: ['/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52798', 'data', 'file=/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpfaybqyq_/f7o7ops4.json', 'init=/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpfaybqyq_/tlim4d49.json', 'output', 'file=/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpfaybqyq_/prophet_modelgi137wae/prophet_model-20240713191445.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2024-07-13T19:14:45.036+0100] {logging_mixin.py:188} WARNING - 19:14:45 - cmdstanpy - INFO - Chain [1] start processing
[2024-07-13T19:14:45.036+0100] {model.py:2058} INFO - Chain [1] start processing
[2024-07-13T19:15:10.701+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-13T19:15:10.725+0100] {process_utils.py:132} INFO - Sending 15 to group 8842. PIDs of all processes in the group: [8846, 8842]
[2024-07-13T19:15:10.725+0100] {process_utils.py:87} INFO - Sending the signal 15 to group 8842
[2024-07-13T19:15:10.750+0100] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-13T19:15:10.762+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T19:15:10.781+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mak/Desktop/Code_With_Me/Sentiment project/dags/dg1.py", line 95, in fit_prediction
    p.fit(fit_data)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/prophet/forecaster.py", line 1232, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/prophet/models.py", line 121, in fit
    self.stan_fit = self.model.optimize(**args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cmdstanpy/model.py", line 644, in optimize
    self._run_cmdstan(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cmdstanpy/model.py", line 2087, in _run_cmdstan
    line = proc.stdout.readline()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-13T19:15:10.927+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hhh, task_id=fit_prediction, run_id=manual__2024-07-13T18:01:49.117943+00:00, execution_date=20240713T180149, start_date=20240713T181438, end_date=20240713T181510
[2024-07-13T19:15:11.257+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=8842, status='terminated', exitcode=2, started='19:14:39') (8842) terminated with exit code 2
[2024-07-13T19:15:11.260+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=8846, status='terminated', started='19:14:45') (8846) terminated with exit code None
