[2024-07-14T18:20:50.977+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T18:20:51.017+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [queued]>
[2024-07-14T18:20:51.028+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [queued]>
[2024-07-14T18:20:51.028+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T18:20:51.041+0100] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_sp500> on 2024-07-14 17:00:00+00:00
[2024-07-14T18:20:51.059+0100] {logging_mixin.py:188} WARNING - /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4582) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T18:20:51.060+0100] {standard_task_runner.py:63} INFO - Started process 4597 to run task
[2024-07-14T18:20:51.064+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pleaserun', 'get_sp500', 'scheduled__2024-07-14T17:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpgi6m6376']
[2024-07-14T18:20:51.066+0100] {standard_task_runner.py:91} INFO - Job 9: Subtask get_sp500
[2024-07-14T18:20:51.125+0100] {task_command.py:426} INFO - Running <TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [running]> on host MAKs-MacBook-Pro.local
[2024-07-14T18:20:51.204+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pleaserun' AIRFLOW_CTX_TASK_ID='get_sp500' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T17:00:00+00:00'
[2024-07-14T18:20:51.208+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T18:20:57.197+0100] {logging_mixin.py:188} WARNING - [*********************100%%**********************]  1 of 1 completed
[2024-07-14T18:20:57.210+0100] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T18:20:57.211+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T18:20:57.216+0100] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pleaserun, task_id=get_sp500, run_id=scheduled__2024-07-14T17:00:00+00:00, execution_date=20240714T170000, start_date=20240714T172051, end_date=20240714T172057
[2024-07-14T18:20:57.251+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T18:20:57.266+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T18:20:57.266+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T18:28:08.215+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T18:28:08.275+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [queued]>
[2024-07-14T18:28:08.286+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [queued]>
[2024-07-14T18:28:08.286+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T18:28:08.298+0100] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_sp500> on 2024-07-14 17:00:00+00:00
[2024-07-14T18:28:08.324+0100] {logging_mixin.py:188} WARNING - /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5099) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T18:28:08.326+0100] {standard_task_runner.py:63} INFO - Started process 5116 to run task
[2024-07-14T18:28:08.328+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pleaserun', 'get_sp500', 'scheduled__2024-07-14T17:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmpqt_1cs7m']
[2024-07-14T18:28:08.330+0100] {standard_task_runner.py:91} INFO - Job 4: Subtask get_sp500
[2024-07-14T18:28:08.444+0100] {task_command.py:426} INFO - Running <TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [running]> on host MAKs-MacBook-Pro.local
[2024-07-14T18:28:08.581+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pleaserun' AIRFLOW_CTX_TASK_ID='get_sp500' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T17:00:00+00:00'
[2024-07-14T18:28:08.586+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T18:28:08.588+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T18:28:08.591+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mak/Desktop/Code_With_Me/Sentiment project/dags/dag1.py", line 125, in get_sp500
    sp = yf.download("^GSPC", start="2022-01-01", end=dt.date.today() + date.timedelta(days = 1))
                                                                        ^^^^
NameError: name 'date' is not defined
[2024-07-14T18:28:08.613+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pleaserun, task_id=get_sp500, run_id=scheduled__2024-07-14T17:00:00+00:00, execution_date=20240714T170000, start_date=20240714T172808, end_date=20240714T172808
[2024-07-14T18:28:08.648+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task get_sp500 (name 'date' is not defined; 5116)
[2024-07-14T18:28:08.680+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T18:28:08.704+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T18:28:08.706+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T18:31:44.757+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T18:31:44.813+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [queued]>
[2024-07-14T18:31:44.821+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [queued]>
[2024-07-14T18:31:44.821+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-14T18:31:44.832+0100] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_sp500> on 2024-07-14 17:00:00+00:00
[2024-07-14T18:31:44.848+0100] {logging_mixin.py:188} WARNING - /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5407) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T18:31:44.850+0100] {standard_task_runner.py:63} INFO - Started process 5429 to run task
[2024-07-14T18:31:44.854+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pleaserun', 'get_sp500', 'scheduled__2024-07-14T17:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmp079gz6au']
[2024-07-14T18:31:44.856+0100] {standard_task_runner.py:91} INFO - Job 4: Subtask get_sp500
[2024-07-14T18:31:44.918+0100] {task_command.py:426} INFO - Running <TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T17:00:00+00:00 [running]> on host MAKs-MacBook-Pro.local
[2024-07-14T18:31:44.987+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pleaserun' AIRFLOW_CTX_TASK_ID='get_sp500' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T17:00:00+00:00'
[2024-07-14T18:31:44.991+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T18:31:44.992+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T18:31:44.993+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mak/Desktop/Code_With_Me/Sentiment project/dags/dag1.py", line 125, in get_sp500
    sp = yf.download("^GSPC", start="2022-01-01", end=dt.date.today() + dt.date.timedelta(days = 1))
                                                                        ^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.date' has no attribute 'timedelta'
[2024-07-14T18:31:45.005+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pleaserun, task_id=get_sp500, run_id=scheduled__2024-07-14T17:00:00+00:00, execution_date=20240714T170000, start_date=20240714T173144, end_date=20240714T173145
[2024-07-14T18:31:45.014+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task get_sp500 (type object 'datetime.date' has no attribute 'timedelta'; 5429)
[2024-07-14T18:31:45.045+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T18:31:45.063+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T18:31:45.063+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
